baseurl = "https://dolphinsandpikkabirds.netlify.app/"
languageCode = "en-uk"
languageLang = "en"
title = "Sumera Priyadarsini"

theme = "hugo-theme-cactus"

colortheme = "white"

[params]
css = ["css/custom.css"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4


#Home Page Settings

description = "Hugo is a general-purpose website framework. Technically speaking, Hugo is a static site generator. Unlike systems that dynamically build a page with each visitor request, Hugo builds pages when you create or update your content. Since websites are viewed far more often than they are edited, Hugo is designed to provide an optimal viewing experience for your website’s end users and an ideal writing experience for website authors."
cv_name = "sumo.pdf"

mainSection = "posts"

showAllPostsOnHomePage = true
postsOnHomePage = 5

tagsOverview = true

showProjectsList = true
projectsUrl = "https://github.com/Sylfrena"

rss = true

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
    name = "github"
    link = "https://github.com/Sylfrena"
[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/company/github/"
[[params.social]]
    name = "twitter"
    link = "https://www.twitter.com/SumoOfShinovar"
[[params.social]]
    name = "email"
    link = "sylphrenadin@gmail.com"  # no need for "mailto:" in the head




copyright = "Sumera" # cactus theme will use site title if copyright is not set

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = [ "taxonomy", "taxonomyTerm"]
